name: Run Pester Tests

# Note: This workflow is not part of the main CI pipeline defined in CI.yaml.
# It is intended for running Pester tests independently.

# on:
#   push:
#     branches:
#       - main
#       - feat/**
#   pull_request:
#     branches:
#       - main

jobs:
  pester-tests:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up PowerShell
      uses: actions/setup-powershell@v2

    - name: Install Pester
      run: |
        Install-Module -Name Pester -Force -Scope CurrentUser

    - name: Run Pester Tests
      run: |
        Invoke-Pester -Path ./WitcherSmartSaveManagerTests -Output Detailed
      shell: pwsh
